apiVersion: v2
name: node-red
description: Deploy node-red service

type: application

version: 0.0.0
appVersion: 1.0.0

dependencies:
  - name: node-red
    version: 0.32.1
    repository: https://schwarzit.github.io/node-red-chart/
